### ISSUE TITLE
The following resource(s) failed to create: [TableauServer]

### ISSUE THREAD

**Issue by etienne-hinfact** [aws-quickstart/quickstart-tableau-server#113]
When creating a new CloudFormation stack based on `tableau-single-server-main.template.yaml`, execution fails.

Error message:

> Embedded stack arn:aws:cloudformation:us-west-2:128489674626:stack/Tableau-Server-TableauStack-PLY7E4U0P251/a7364520-4fb5-11ed-8f10-06e58235caa5 was not successfully created: The following resource(s) failed to create: [TableauServer].

I chose Linux as OS.

**Comment by madhumita-bharde** [comment]
"Unless you are customizing the Quick Start templates for your own projects, don’t change the default settings for the following Amazon Simple Storage Service (Amazon S3) parameters: Quick Start S3 bucket name, Quick Start S3 bucket Region, and Quick Start S3 key prefix. Changing these settings automatically updates code references to point to a new Quick Start location. For more information, refer to the [AWS Quick Start Contributor’s Guide](https://fwd.aws/NwqYA?)."

https://aws-quickstart.github.io/quickstart-tableau-server/

**Comment by vsnyc** [comment]
Based on the latest test results: https://github.com/aws-quickstart/quickstart-tableau-server/pull/116#pullrequestreview-1581504840, this should no longer be an issue.
