### ISSUE TITLE
Function name

### ISSUE THREAD

**Issue by peatey** [aws-quickstart/quickstart-tableau-server#24]
HI Guys,

Can I please confirm if the function in the Linux stack the worker script calls:
`"send_singal_to_topologyWaitHandle() {",
                                                    "# Signal successful completion",
                                                    {
                                                        "Fn::Sub": "/opt/aws/bin/cfn-signal -e $? '${TopologyWaitHandle}'"
                                                    },
                                                    "}",
                                                    "set_topology",
                                                    "unset -f set_topology",
                                                    "trap send_singal_to_topologyWaitHandle EXIT"`

is meant to be `send_singal_to_topologyWaitHandle `

or `send_signal_to_topologyWaitHandle `

thanks!

**Comment by vsnyc** [comment]
This is no longer relevant.
