### ISSUE TITLE
WorkerWaitCondition

### ISSUE THREAD

**Issue by jeremypumphrey** [aws-quickstart/quickstart-tableau-server#25]
Stack failed to create with the following error. Is this an error in execution or something I can fix on my side? Not sure what it means and the substack with details gets deleted. 

Embedded stack arn:aws:cloudformation:us-east-1:564062160093:stack/Tableau-Server-WorkloadStack-1RV8H8I72BC99/0133b5a0-94ce-11e8-9b56-503aca261699 was not successfully created: The following resource(s) failed to create: [ServerLoadBalancer, WorkerWaitCondition, IPAssoc].

**Comment by vsnyc** [comment]
Could you disable the rollback and retry? With this option, the nested stack won't get deleted when you run into an error, see troubleshooting section in [the guide](https://aws-quickstart.s3.amazonaws.com/quickstart-tableau-server/doc/tableau-server-on-the-aws-cloud.pdf).

After that you can log on to the Tableau EC2 instances to see the cause of error. For windows, the log files are at C:\cfn\log\ and for linux: /var/log/cfn-\*.log, /var/log/cloud-\*.log

**Comment by jeremypumphrey** [comment]
Good tip, thanks.
