### ISSUE TITLE
Nested stack fails if Marketplace terms are not accepted

### ISSUE THREAD

**Issue by mpoens** [aws-quickstart/quickstart-tableau-server#26]
On first invocation of the single server linux stack, the nested stack invocation rolled back, resulting in a failure of the parent stack. On investigation we found in the cloudformation logs:

12:43:57 UTC+0100 | CREATE_FAILED | AWS::EC2::Instance | TableauServer | In order to use this AWS Marketplace product you need to accept terms and subscribe. To do so please visit https://aws.amazon.com/marketplace/pp?sku=aw0evgkw8e5c1q413zgy5pjce (Service: AmazonEC2; Status Code: 401; Error Code: OptInRequired; Request ID: 8b468c50-1099-4305-aa64-317ed74f59a4)
-- | -- | -- | -- | --

As part of our investigation our experience was that this warning message only appears the first time the stack invocation is attempted - we had to recover this info from the list of deleted stacks in cloudformation. As far as we observed, https://aws-quickstart.s3.amazonaws.com/quickstart-tableau-server/doc/tableau-server-on-the-aws-cloud.pdf does not capture this point.

**Comment by agamzn** [comment]
Thanks for the feedback. The marketplace subscription is a prerequisite to launching the stack. Looking over the documentation, I see an opportunity to better define this. 

We'll add this to our roadmap and the documentation should be updated shortly.  Leaving open for tracking.

**Comment by vsnyc** [comment]
We have added a note in the documentation to reflect this.

If you are using the CentOS operating system, subscribe to the [CentOS AMI in AWS Marketplace](https://aws.amazon.com/marketplace/pp/B00O7WM7QW).
