### ISSUE TITLE
Stack uses old Classic Load Balancer

### ISSUE THREAD

**Issue by jeremypumphrey** [aws-quickstart/quickstart-tableau-server#28]
The stack uses the deprecated classic load balancer rather than the modern ALB. Can it be modernized to get the features such as WAF support that ALB has that classic LB doesn't?

Auto Scaling Group: Tableau-Server-WorkloadStack-1QWKC4SWJS1JU-WorkerGroup-XFN9F9PBBPYR
ELB: Tableau-S-ServerLo-1VBKW2Z3UJDTW

I deleted the ELB and replaced with an ALB outside of cloud-formation in my environment after running the stack, but I'm pretty sure there is a reference in the ASG to the ELB so I probably broke the ASG setup.

**Comment by JohnLahr** [comment]
If you're using the Linux cluster template, I have an open [pull request](https://github.com/aws-quickstart/quickstart-tableau-server/pull/40) that replaces the Classic Load Balancer with an Application Load Balancer. ([alternate gist link](https://gist.github.com/JohnLahr/f17d8acb350ba7fc8628bd8cf3aefaeb))

**Comment by vsnyc** [comment]
This is no longer relevant.
