### ISSUE TITLE
single-server Linux quickstart creates new VPC - incorrect documentation of options?

### ISSUE THREAD

**Issue by bzip2** [aws-quickstart/quickstart-tableau-server#35]
Hi. 

The option to install a standalone server on Linux appears to be described incorrectly both on [github](https://github.com/aws-quickstart/quickstart-tableau-server) and at [amazon.com](https://aws.amazon.com/quickstart/architecture/tableau-server/). It's described only as deploying the stack into the default VPC, but it created a new VPC for me. I'm happy to be up and running so it was not a problem, but I wonder if either the guides are out of date (i.e., referring to `tableau-single-server.template` instead of `tableau-cluster-linux-master.template`), or my architecture somehow presents an unusual condition that leads to a new VPC. Since `tableau-cluster-linux-master.template` invokes `aws-vpc.template` but `tableau-single-server.template` does not, the creation of a new VPC looks like the expected result.

Here's what I did:

1. On the [Tableau quickstart page](https://aws.amazon.com/quickstart/architecture/tableau-server/), select "How to deploy" then "Deploy a standalone Tableau Server environment (uses your default VPC)" option.
2. Change the region, use Ubuntu, add the CIDR of my office, choose user IDs for tsm admin and ts admin, set the instance type to m4.2xlarge.
3. Go.

Result: CloudFormation is successful. Output includes server URLs and VPC ID. VPC dashboard shows a new, non-default VPC with all its tags set by CloudFormation. The stack launched only one new instance, confirming that this is the standalone option.

**Comment by vsnyc** [comment]
This is no longer relevant.
