### ISSUE TITLE
undocumented step in Linux standalone server setup

### ISSUE THREAD

**Issue by bzip2** [aws-quickstart/quickstart-tableau-server#36]
Hello.

I was able to run the Linux standalone server quickstart successfully (using Ubuntu), but encountered the following hurdles that weren't documented in the deployment guide.

1. When I connected to the Tableau Services Manager URL output by CloudFormation (https://#.#.#.#:8850/#/status), my browser complained that the connection was not secure, and I had to add a security exception. The discussion of SSL certificates in the deployment guide appears to be related to inter-instance communication in a cluster setup.

2. After I logged in as tsmadmin and various configurations were deployed in a window resembling a terminal, I got a message like "installation is incomplete - someone with admin access must connect to the instance with localhost". It took me a while to find the solution, which is to execute `tabcmd initialuser --server 'localhost:80' --username 'tsadmin'`, but the user executing this must be a member of both the sudo and tsmadmin groups. If that condition is not true, the error messages from tabcmd are misleading.

Does it sound as if I missed a required step in the setup?

**Comment by bzip2** [comment]
Hello.

I was able to run the Linux standalone server quickstart successfully (using Ubuntu), but encountered the following hurdles that weren't documented in the deployment guide.

1. When I connected to the Tableau Services Manager URL output by CloudFormation (https://#.#.#.#:8850/#/status), my browser complained that the connection was not secure, and I had to add a security exception. The discussion of SSL certificates in the deployment guide appears to be related to inter-instance communication in a cluster setup.

2. After I logged in as tsmadmin and various configurations were deployed in a window resembling a terminal, I got a message like "installation is incomplete - someone with admin access must connect to the instance with localhost". It took me a while to find the solution, which is to execute `tabcmd initialuser --server 'localhost:80' --username 'tsadmin'`, but the user executing this must be a member of both the sudo and tsmadmin groups. If that condition is not true, the error messages from tabcmd are misleading.

Does it sound as if I missed a required step in the setup?

**Comment by jkonkol** [comment]
Was your second issue solved by adding your tsadmin user to both of those groups?

I am using Active Directory and I'm at the point where it's saying someone must connect with localhost.

**Comment by bzip2** [comment]
> Was your second issue solved by adding your **tsadmin** user to both of those groups?

My issue was resolved (i.e., I was able to execute the tabcmd command above, and then the web installation proceeded automatically) when I added **tsmadmin** (the user) to the tsmadmin group and to the sudo group.

**Comment by vsnyc** [comment]
This is no longer relevant.
