### ISSUE TITLE
You must specify an allocation id when mapping an address to a VPC instance

### ISSUE THREAD

**Issue by reorg-hhasibul** [aws-quickstart/quickstart-tableau-server#37]
We are getting this error on AWS Centos. we created a brand new VPC.

You must specify an allocation id when mapping an address to a VPC instance (Service: AmazonEC2; Status Code: 400; Error Code: InvalidParameterCombination; Request ID: ****

**Comment by mykhailo-neredko-zaelab** [comment]
Same from my side. New VPC created by stack and error during creation:
![image](https://user-images.githubusercontent.com/32634579/54752572-4ba2cd80-4be7-11e9-9299-1a71e78198e2.png)

is there any workaround for this issue?

**Comment by zaqk** [comment]
Any updates on this? Running into this issue as well.

**Comment by zaqk** [comment]
@reorg-hhasibul and @mykhailo-neredko-zaelab I was able to mitigate this by editing the cloudfront template EIP resource. 

I added `Domain` to the `Properties` attribute of the `EIP` resource. I believe it has to do with running this cloudformation template in a private subnet. The template requires a public subnet but this isn't very practical. I believe this template should default to using a private subnet as that's probably the most common use case.

`
...       
 "EIP": {
            "Type": "AWS::EC2::EIP",
            "Properties": {
                "InstanceId": {
                    "Ref": "TableauServer"
                },
                "Domain": "vpc"
            }
        },
...
`

**Comment by vsnyc** [comment]
Thanks for the research @zaqk. Would you like to create a pull request for the change? We can test that through our CI and merge. 

Regarding the instance placement in public subnet, the single deployment scenario is meant to be used for demo/testing. If you want something robust, you can checkout the cluster options described [here] (https://aws.amazon.com/quickstart/architecture/tableau-server/) and the corresponding templates in this repo. The cluster version will create instances in the private subnets in 3 AZs and expose a Load Balancer DNS to access the server.

**Comment by vsnyc** [comment]
This has been fixed in commit https://github.com/aws-quickstart/quickstart-tableau-server/commit/81a007c9c25e5dccffc7ae8fe981b771070b869f.
