### ISSUE TITLE
Security Group Suggestion

### ISSUE THREAD

**Issue by jkonkol** [aws-quickstart/quickstart-tableau-server#39]
I would propose using the Security Group of the Load Balancer for traffic (80 & 443) between the LB and the Worker Servers, then the Security Group of the Servers for intra-server traffic (0-65535). I would also remove Port 22 as these servers are on a Private subnet.

This caused me an issue because I use different subnets for our Public vs Private subnets within the same VPC.

I will attach an updated version of tableau-cluster-linux.template as a suggestion when I am done testing.

**Comment by vsnyc** [comment]
This is no longer relevant.
