### ISSUE TITLE
SilentInstaller.py config file for active directory instance store

### ISSUE THREAD

**Issue by pashafirdous** [aws-quickstart/quickstart-tableau-server#42]
Hi ,

I need to enable "Active Directory" Instance store with the silent installer script.
i cna pretty clearly get the "local" instance store working with the silent installer script, but the active directry fails.

i'm using the below as config file:
{
 "configEntities":{
  "identityStore": {
   "_type": "identityStoreType",
   "type": "activedirectory",
   "domain": "domainx.com",
   "nickname": "domainx.com",
   }
  }
}

**Comment by vsnyc** [comment]
This is no longer relevant.
