### ISSUE TITLE
VPCStack fails to createvfor single-server-master.template

### ISSUE THREAD

**Issue by PrasBiswas** [aws-quickstart/quickstart-tableau-server#47]
The following resource(s) failed to create: [VPCStack]. . Rollback requested by user.
templates/tableau-single-server-master.template

Embedded stack arn:aws:cloudformation:ca-central-1:281621781242:stack/TableauSingleNodeWindowsInstall-VPCStack-1C5FZ94RP4S7H/86aea220-92ad-11e9-80f7-0607b10fa94c was not successfully created: The following resource(s) failed to create: [PublicSubnet2, PublicSubnet1, PublicSubnetRouteTable, VPCGatewayAttachment].

**Comment by vsnyc** [comment]
Sorry for the late response, is this still an issue? If so, could you post the parameters used and the CloudFormation events? What was the first resource that failed, it should give you an indicative error message.

**Comment by vsnyc** [comment]
This is no longer relevant.
