### ISSUE TITLE
When I tried to replace installer for windows cluster deployment, I find there is worker installer and server installer but in our internal tableau release we only have one server installer for a cluster, is this because this template out of date? I'm from tableau btw

### ISSUE THREAD

**Issue by Taitanguo** [aws-quickstart/quickstart-tableau-server#48]

**Comment by vsnyc** [comment]
Yes, this is the 2018.x installer. I have received a new Windows Cluster template from @vkbronjames, but it needs to be refactored to put back in the Quick Start.

**Comment by Taitanguo** [comment]
Yeah sure, please include me in it. I'm from Tableau and we have internal need for automate set up server on aws have everything in code.

**Comment by vsnyc** [comment]
This is no longer relevant.
