### ISSUE TITLE
Required CloudFormation parameters should be marked as such in the template

### ISSUE THREAD

**Issue by slorion** [aws-quickstart/quickstart-tableau-server#50]
It is not customary to specify the state for my office address, only the postal code. Leaving the state parameter blank causes the installation to fail and the CloudFormation stack to rollback. Also, having access to the Tableau Server installation logs would have made debugging this issue a lot simpler.

**Comment by vsnyc** [comment]
Closing older issues

**Comment by slorion** [comment]
I quickly looked at the code and don't see a fix for this? It would be more user friendly to validate mandatory parameters before executing the template.
