### ISSUE TITLE
Migrate from `AmazonEC2RoleforSSM` to `AmazonSSMManagedInstanceCore`

### ISSUE THREAD

**Issue by rrmistry** [aws-quickstart/quickstart-tableau-server#58]
After my Cloud Formation stack got deployed, I was checking the Tableau IAM role policies for [`AmazonEC2RoleforSSM`](https://console.aws.amazon.com/iam/home?#/policies/arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM$serviceLevelSummary) and I noticed this:
> | **Description** | This policy will soon be deprecated. Please use AmazonSSMManagedInstanceCore policy to enable AWS Systems Manager service core functionality on EC2 instances. For more information see https://docs.aws.amazon.com/systems-manager/latest/userguide/setup-instance-profile.html |
> |---|---|

------------------

I'll try to run a copy of this template with [`AmazonSSMManagedInstanceCore`](https://console.aws.amazon.com/iam/home?region=us-east-2#/policies/arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore$serviceLevelSummary) IAM role policy. If everything works smoothly and I have time then I'll send a pull-request.

Thanks!

**Comment by vsnyc** [comment]
Thank you for opening this issue. I have added the change in the develop branch, see commit: https://github.com/aws-quickstart/quickstart-tableau-server/commit/3d80e5aad2a7b659c1aa9a96e6f303c5f92c631a. It will be merged to master and pushed to live after testing. Currently working with Tableau to get that sorted. Will update the issue when that's resolved.

**Comment by vsnyc** [comment]
This change is now tested, merged and pushed to the live template links.
