### ISSUE TITLE
Tableau Single-Server Fails for EIP

### ISSUE THREAD

**Issue by sdorazio** [aws-quickstart/quickstart-tableau-server#61]
Tableau Single-Server (Ubuntu) Cloudformation template fails when associating the running instance with an elastic IP:

`You must specify an allocation id when mapping an address to a VPC instance (Service: AmazonEC2; Status Code: 400; Error Code: InvalidParameterCombination; Request ID: 72deff9b-df66-454a-91e4-8213b3e55813)`

**Comment by vsnyc** [comment]
This was first reported in #37 and is fixed by commit https://github.com/aws-quickstart/quickstart-tableau-server/commit/81a007c9c25e5dccffc7ae8fe981b771070b869f. Please try again.
