### ISSUE TITLE
Deployment of Tableau Cluster in New VPC failed

### ISSUE THREAD

**Issue by sananthurama** [aws-quickstart/quickstart-tableau-server#66]
Deployment of Tableau Cluster in the New VPC failed with the Topology Wait condition

AWS Support ticket raised and they are able to resolve the issue.  Please update the template from your and confirm.

The issue was with the QuickStart template provided by Tableau where the TopologyWaitHandle was unable to receive the success signal from the PrimarySever resource

Here is the changes made to the template:

The TopologyWaitCondition resource is created after the PrimaryServer has created successfully. 
In that case, since the PrimaryServer resource has already sent a success signal, the TopologyWaitCondition resource is waiting for an already received signal. 
In the UserData section, there is no cfn-signal being sent to the TopologyWaitHandle resource. 
Added the cfn-signal for the TopologyWaitHandle resource in the UserData section 
There is the cfn-signal command in the /tmp/workers.sh file in the Init section but the .sh script never gets called and thus the TopologyWaitHandle resource does not receive the success signal.

**Comment by kglover29** [comment]
Hi @sananthurama if the cluster deployment doesn't complete the deployment will fail. Can you post logs from /var/log/messages that came from cloud-init?
