### ISSUE TITLE
Tableau installation verbose logs Linux Cloudformation

### ISSUE THREAD

**Issue by dayyehm** [aws-quickstart/quickstart-tableau-server#69]
When changing the instance type with less hardware than required instance send a failure signal , part of the userdata script failed to finish ( apparently no logs to point to that in cloud-init).

Is it possible to enable those logs in the solution so that customers does not have to modify the userdata scripts in the template or maybe modify the tableau installation commands to log installation errors.

The issue was CFN was receiving a failure signal due to incomplete installation but cloud-init and cfn-init had no details about the failure.

**Comment by vsnyc** [comment]
I wasn't able to reproduce this. In general, the following information and log files can be gathered to troubleshoot issues. Some maybe missing if the installation fails early.

1. Set of parameters used for a new VPC deployment (redacting the Tableau license key)

2. From the primary tableau server, the following log files
   a. /var/log/messages 
   b. /var/log/cfn-init.log
   c. /var/log/cloud-init.log
   d. /root/.tableau/tsm/tsm.log
   e. /var/opt/tableau/tableau_server/logs/app-install.log
   f. zip file generated by the output of: tsm maintenance ziplogs. The default location is /var/opt/tableau/tableau_server/data/tabsvc/files/log-archives/logs.zip

3. From the worker nodes, the following log files
   a. /var/log/messages
   b. /var/log/cfn-init.log
   c. /var/log/cloud-init.log 
   d. /var/opt/tableau/tableau_server/logs/app-worker-install.log

**Comment by vsnyc** [comment]
I just discovered that there is another file to watch out for:
* /var/opt/tableau/tableau_server/data/tabsvc/logs/tabadmincontroller/tabadmincontroller_*.log
