### ISSUE TITLE
Quickstart is not installing Tableau

### ISSUE THREAD

**Issue by fleita9** [aws-quickstart/quickstart-tableau-server#72]
I created an instance in sa-east-1 through the quickstart. 
Everything worked as expected. The stacks are completed:

![image](https://user-images.githubusercontent.com/8388967/77561190-26e9d180-6e9d-11ea-845d-67631db0c494.png)

and in the outputs I have the URL's to start configuring the server:

![image](https://user-images.githubusercontent.com/8388967/77561461-7b8d4c80-6e9d-11ea-8773-2033120d710d.png)

But when I try to enter the administration site, in the 8850 port, the site can't be reached:
![image](https://user-images.githubusercontent.com/8388967/77561574-a8416400-6e9d-11ea-9081-bd02cc0e81d8.png)

So I went to the terminal and ssh to the instance and tried to see the tsm status and is not installed:

![image](https://user-images.githubusercontent.com/8388967/77561865-0c642800-6e9e-11ea-8f29-e9a895ad7330.png)

So I went to the opt directory to see the tableau directory but found only the aws folder.
![image](https://user-images.githubusercontent.com/8388967/77562063-4b927900-6e9e-11ea-8b37-bde7006316b6.png)

Don't know what is going on. Seems thtat everything is created but Tableau is not installed

Thanks in advance

**Comment by vsnyc** [comment]
@fleita9 - Hi, the tableau server is installed and you should be able to reach it by going to the `TableauServerURL` in the output. Did that work for you?

Looks like this would be:
http://18.229.252.215/

Accessing the TSM Web UI is slightly complicated, I need to refresh my memory, will get back.

**Comment by vsnyc** [comment]
Sorry for the delay, here are the instructions to access the TSM interface. I'm resolving this issue, please open a new one if you have more questions.

1. Setup a tunnel on your local device to forward port 8850 on the server, e.g.,
`ssh -i /path/to/your/private-key.pem -L 8850:localhost:8850 ubuntu@18.229.252.215`

2. Access the TSM Web UI on your device browser by going to `https://127.0.0.1:8850/`. Ignore any SSL warnings that show up. See example screenshot.

![TSM-web-ui-tunnel](https://user-images.githubusercontent.com/624297/79375652-f559a880-7f26-11ea-85c3-f40a029352fb.png)
