### ISSUE TITLE
AcceptEULA allowed value error

### ISSUE THREAD

**Issue by jduke99** [aws-quickstart/quickstart-tableau-server#73]
I keep getting this error when trying to set up:

![image](https://user-images.githubusercontent.com/5069947/78519048-146e7280-7790-11ea-9d6d-f48163139c67.png)

Ideas?

**Comment by JamesSWiggins** [comment]
I believe this issue is addressed by this pull request:  https://github.com/aws-quickstart/quickstart-tableau-server/pull/74

**Comment by vsnyc** [comment]
@jduke99 - I had a chat with @JamesSWiggins regarding this. It is possible that the source template you launched from and the nested template that was invoked was out of sync. I'm investigating it.

Meanwhile, could you retry this from one of the launch links at the quick start page and see if you run into any issues?
https://aws.amazon.com/quickstart/architecture/tableau-server/

If you do again, please let me know the link you used and the set of parameters you passed (redacting the license key and personal registration information). 

Thanks!

**Comment by vsnyc** [comment]
The Marketplace template links have been updated.
