### ISSUE TITLE
Tableau-cluster-linux Cloudformation template failing while creating bastion autoscaling group

### ISSUE THREAD

**Issue by uttam-kr** [aws-quickstart/quickstart-tableau-server#75]
The following resource(s) failed to create: [BastionAutoScalingGroup].

BastionAutoScalingGroup CREATE_FAILED Received 1 FAILURE signal(s) out of 1. Unable to satisfy 100% MinSuccessfulInstancesPercent requirement

log from bastionHost:-

grep -ni 'error\|failure' $(sudo find /var/log -name cfn* -or -name cloud-init*) /var/log/cloud-init.log:458:Apr 22 08:19:08 cloud-init[3012]: main.py[DEBUG]: Ran 13 modules with 0 failures /var/log/cloud-init.log:560:Apr 22 08:19:19 cloud-init[3208]: main.py[DEBUG]: Ran 10 modules with 0 failures /var/log/cloud-init.log:594:ProcessExecutionError: Unexpected error while running command. /var/log/cloud-init.log:615:RuntimeError: Runparts: 1 failures in 1 attempted commands /var/log/cloud-init.log:651:Apr 22 08:20:09 cloud-init[3415]: main.py[DEBUG]: Ran 9 modules with 1 failures /var/log/cloud-init-output.log:212:--> Processing Dependency: perl(Error) for package: perl-Git-2.23.1-1.amzn2.0.2.noarch /var/log/cloud-init-output.log:215:---> Package perl-Error.noarch 1:0.17020-2.amzn2 will be installed /var/log/cloud-init-output.log:230: perl-Error noarch 1:0.17020-2.amzn2 amzn2-core 32 k /var/log/cloud-init-output.log:249: Installing : 1:perl-Error-0.17020-2.amzn2.noarch 3/8 /var/log/cloud-init-output.log:261: Verifying : 1:perl-Error-0.17020-2.amzn2.noarch 7/8 /var/log/cloud-init-output.log:272: perl-Error.noarch 1:0.17020-2.amzn2 /var/log/cloud-init-output.log:842:Error occurred during build: Command b-bootstrap failed /var/log/cfn-init.log:20:2020-04-22 08:20:08,653 [ERROR] Command b-bootstrap (./bastion_bootstrap.sh --banner https://aws-quickstart.s3.us-east-1.amazonaws.com/quickstart-linux-bastion/scripts/banner_message.txt --enable false --tcp-forwarding false --x11-forwarding false) failed /var/log/cfn-init.log:35:2020-04-22 08:20:08,654 [ERROR] Error encountered during build of config: Command b-bootstrap failed /var/log/cfn-init.log:42: raise ToolError(u"Command %s failed" % name) /var/log/cfn-init.log:43:ToolError: Command b-bootstrap failed /var/log/cfn-init.log:44:2020-04-22 08:20:08,656 [ERROR] -----------------------BUILD FAILED!------------------------ /var/log/cfn-init.log:45:2020-04-22 08:20:08,660 [ERROR] Unhandled exception during build: Command b-bootstrap failed /var/log/cfn-init.log:58: raise ToolError(u"Command %s failed" % name) /var/log/cfn-init.log:59:ToolError: Command b-bootstrap failed /var/log/cfn-init.log:61:2020-04-22 08:20:08,882 [DEBUG] Signaling resource BastionAutoScalingGroup in stack Tableau-ubuntu-BastionHost-1FMT6T80AVICN with unique ID i-0ba02ad1171cdc569 and status FAILURE /var/log/cfn-wire.log:3:2020-04-22 08:20:08,938 [DEBUG] Response: 200 https://cloudformation.us-east-2.amazonaws.com/?Status=FAILURE&ContentType=JSON&StackName=Tableau-ubuntu-BastionHost-1FMT6T80AVICN&Version=2010-05-15&UniqueId=i-0ba02ad1171cdc569&Action=SignalResource&LogicalResourceId=BastionAutoScalingGroup [headers: {'x-amzn-requestid': '9a5ea98d-c6bb-49c9-a6d1-0b663848c9f3', 'date': 'Wed, 22 Apr 2020 08:20:08 GMT', 'content-length': '100', 'content-type': 'application/json'}] /var/log/cfn-init-cmd.log:23:2020-04-22 08:20:08,653 P12339 [ERROR] Exited with error code 6

logs from primary:-

grep -ni 'error\|failure' $(sudo find /var/log -name cfn* -or -name cloud-init*) /var/log/cloud-init-output.log:2099:There are 1 topology validation errors/warnings. /var/log/cloud-init-output.log:2113:There are 1 topology validation errors/warnings. /var/log/cloud-init-output.log:2127:There are 1 topology validation errors/warnings. /var/log/cloud-init-output.log:2141:There are 1 topology validation errors/warnings. /var/log/cloud-init-output.log:2155:There are 1 topology validation errors/warnings. /var/log/cloud-init-output.log:2169:There are 1 topology validation errors/warnings. /var/log/cloud-init-output.log:2183:There are 1 topology validation errors/warnings. /var/log/cloud-init-output.log:2197:There are 1 topology validation errors/warnings. /var/log/cloud-init-output.log:2211:There are 1 topology validation errors/warnings. /var/log/cloud-init-output.log:2225:There are 1 topology validation errors/warnings. /var/log/cloud-init-output.log:2239:There are 1 topology validation errors/warnings. /var/log/cloud-init-output.log:2254:There are 1 topology validation errors/warnings. /var/log/cloud-init-output.log:2268:There are 1 topology validation errors/warnings. /var/log/cloud-init-output.log:2281:There are 2 topology validation errors/warnings. /var/log/cloud-init-output.log:2305:There are 3 topology validation errors/warnings. /var/log/cloud-init-output.log:2475:There are 3 topology validation errors/warnings. /var/log/cloud-init-output.log:2485:Error: This configuration is invalid. Configuring Backgrounder node roles for /var/log/cloud-init-output.log:2496:Error: This configuration is invalid. Configuring Backgrounder node roles for /var/log/cloud-init.log:856:2020-04-22 08:18:10,148 - main.py[DEBUG]: Ran 15 modules with 0 failures /var/log/cloud-init.log:981:2020-04-22 08:18:23,213 - main.py[DEBUG]: Ran 14 modules with 0 failures /var/log/cloud-init.log:1078:cloudinit.util.ProcessExecutionError: Unexpected error while running command. /var/log/cloud-init.log:1105:RuntimeError: Runparts: 1 failures in 1 attempted commands /var/log/cloud-init.log:1141:2020-04-22 08:39:47,298 - main.py[DEBUG]: Ran 20 modules with 1 failures

**Comment by vsnyc** [comment]
The issue with the bastion stack not completing must have been something temporary as we were working on updating the S3 URLs to use regional endpoints. I've tested this and wasn't able to reproduce. Please retry and open a new issue if it happens again.
