### ISSUE TITLE
Mutli-node server install requires Tableau Server Management Add-on

### ISSUE THREAD

**Issue by cameronbarker1** [aws-quickstart/quickstart-tableau-server#79]
I am currently not able to install a 2020.1 or 2020.2 stack as Tableau Server Management Add-on is required and is not enabled for our license keys. A ticket with Tableau has been opened and they have replied with this:

As we discussed, upon review of the Tableau Server logs, it was identified that during the CloudFormation installation, the backgrounders are being configured with specific roles when the number of nodes is greater than 2. However assigning roles for Backgrounders requires the Data Management Add-on, and that is not specified as a hard requirement for using the CloudFormation Template. The result is that the configuration fails because the current key doesn't have the Data Management Add-on.

With Tableau not requiring the Data Management Add-on, yet the CloudFormation template has stipulations for a key with the add on (specifically for deployments with nodes greater than 2), we've found the issue resides with the code of the template. To resolve the issue, a bug report will need to be filed on the Github site for the template.

This can be fixed by changing lines 713 -717.

This code customizes the backgrounder node roles without checking to see if a data management add-on license is present. Since the Data Management is not a requirement, these customization should not be made or should only happen when it is verified that the Data Management Add on License is present. 

(CloudFormation Tableau Template
https://github.com/aws-quickstart/quickstart-tableau-server/blob/master/templates/tableau-cluster-linux.template)

![image](https://user-images.githubusercontent.com/66379174/83687879-1008df00-a5b2-11ea-81ec-91ddc089f920.png)

**Comment by vsnyc** [comment]
@cameronbarker1 - thank you for reporting this. I had sent an email about this to @kglover29 and was waiting for a response.

Do you know what the resolution on lines 713-717 is? I don't know if there is an easy way to add a check the license entitlements and whether the action is allowed, will simply removing the following snippet work?

```
if [ $tsm_nodes -gt 2 ]; then
    tsm topology set-node-role --nodes node1 --role all-jobs
    tsm topology set-node-role --nodes node2 --role no-flows
    tsm topology set-node-role --nodes node3 --role flows
fi
```

**Comment by cameronbarker1** [comment]
Hello vsnyc, I have tried to remove that snippet of code and the template wouldn't work in AWS for some reason, Tableau has responded to my question about if they have a potential fix and they said:
I've reached back out to a few resources on a potential fix for the code. Unfortunately, my resources are depleted and we weren't able to come to a resolution. This stems from the fact that our training pertains to troubleshooting Tableau software and coding isn't part of that training. 
Here's hoping that the recent developments of the new template means someone is actively monitoring the issue page and the bug report gets a quick fix.

So it looks like it is on us, I've been researching a bit more on potential roles I can use instead to workaround this issue and I am currently deploying and testing a few different changes.

**Comment by cameronbarker1** [comment]
I edited my original post and found that you can set the roles to all-jobs and it should work(testing now), and I've also reached out to Tableau to see if there's a way to check if you have an old license type or a new license type easily.

**Comment by vsnyc** [comment]
Thanks for the research @cameronbarker1 . A pull request is welcome with the suggest changes in the template if you are able to resolve it.

**Comment by vsnyc** [comment]
@kglover29 - Kevin, please review this thread and advise on a fix. Thanks!

**Comment by cameronbarker1** [comment]
I've confirmed that setting each nodes role to all-jobs works, I am in contact with Tableau trying to find a good way of seeing if we can differentiate between different license types.
                          tsm topology set-node-role --nodes node1 --role all-jobs
                          tsm topology set-node-role --nodes node2 --role all-jobs
                          tsm topology set-node-role --nodes node3 --role all-jobs

**Comment by cameronbarker1** [comment]
Tableau will no longer help with this matter and will not provide a way to identify different types of licenses, it seems that I will just have to use the workaround from now on.

**Comment by vsnyc** [comment]
This is no longer relevant.
