### ISSUE TITLE
Ubuntu 18.04 as an AMIOS

### ISSUE THREAD

**Issue by dotsdl** [aws-quickstart/quickstart-tableau-server#80]
Since Ubuntu 16.04 is nearing the end of its maintenance window (April 2021), is there interest in making Ubuntu 18.04 an [allowed AMIOS](https://github.com/aws-quickstart/quickstart-tableau-server/blob/master/templates/tableau-single-server.template#L106)? Do we anticipate this would require many changes to the installation pathway?

**Comment by vsnyc** [comment]
This is no longer relevant.
