### ISSUE TITLE
Windows_Server-2012-R2_RTM-English-64Bit-Base-2019.07.12 AMIs deprecated

### ISSUE THREAD

**Issue by amzcarlli** [aws-quickstart/quickstart-tableau-server#81]
## 1. Title
AMIs in tableau-single-server-windows.template are deprecated and need update AMI IDs.

## 2. Description
Stack creation in us-east-1 results in "API: ec2:RunInstances Not authorized for images: [ami-094a644f1fb9e4ce3]"
Windows_Server-2012-R2_RTM-English-64Bit-Base-2019.07.12 has been deprecated.

**Comment by vsnyc** [comment]
@amzcarlli - sorry for the delay. I've changed the behavior to use the latest AMI using a SSM parameter. See commit: https://github.com/aws-quickstart/quickstart-tableau-server/commit/ec7b754e89452db7fd9a795dfeeed73df34f4c5d. The public launch links will be updated once the tests pass and merge.
