### ISSUE TITLE
Windows Cluster Template  - New VPC - WorkloadStack Create_Failed - Template Error

### ISSUE THREAD

**Issue by mjsomar** [aws-quickstart/quickstart-tableau-server#83]
Hi,
When I use the CFT for a windows cluster I receive the following error ~ 4 minutes into the build:
**Template error: Mapping named 'AWSAMIRegionMap' is not present in the 'Mappings' section of template.**

I've performed the following:
- Re-read the PDF to ensure I wasn't missing any of the required fields
- Changed up a few of the variables, like the bucket name, availability zones selected, etc.
- Saw that the template does not reference the latest AMI for W2012 R2 and so updated that value for the region I'm building in
- Looked for naming inconsistencies in the template for 'Mappings' and 'AWSAMIRegionMap'

Is this error misleading or is there genuinely an issue in the Mappings section?

**Comment by sudharsansadasivam** [comment]
Is this Resolved ? @mjsomar 

I also see the same error 
Windows Cluster Template - New VPC - WorkloadStack Create_Failed - Template Error

**Comment by vsnyc** [comment]
This is no longer relevant.
