### ISSUE TITLE
tableau-cluster-windows.template-ami-0b90712bab07bff79-ap-southeast-2-not authorized

### ISSUE THREAD

**Issue by mayuraj** [aws-quickstart/quickstart-tableau-server#84]
Hi,

It looks like tableau-cluster-windows.template is missing the Mapping for **AWSAMIRegionMap:**

I have added the mapping from tableau-cluster-windows-master.template however, the AMI for **ap-southeast-2** seems to be deprecated and CloudFormation is giving below error.

**API: ec2:RunInstances Not authorized for images: [ami-0b90712bab07bff79]**

Can someone confirm if the AMI's are correct and update the correct AMI if possible.

Thanks
Mayur

**Comment by vsnyc** [comment]
This is no longer relevant.
