### ISSUE TITLE
Support for 2020.4 and Postgres 13

### ISSUE THREAD

**Issue by jreading** [aws-quickstart/quickstart-tableau-server#88]
Sounds like Postgres 12+ is not supported until version 2020.4. Are there plans to add this?

**Comment by kglover29** [comment]
Yes. We are making changes to the template to always pull the latest release, and subsequently Postgres 12+. 
[See PR 89](https://github.com/aws-quickstart/quickstart-tableau-server/pull/89)

**Comment by vsnyc** [comment]
Closing old issues
