### ISSUE TITLE
Tableau Server Fails to create with error - Failed to receive 1 resource signal(s) within the specified duration

### ISSUE THREAD

**Issue by sudharshan1992** [aws-quickstart/quickstart-tableau-server#91]
Hi All,

I'm using the Tableau Quick Start template for Ubuntu Single Server (https://github.com/aws-quickstart/quickstart-tableau-server/blob/main/templates/tableau-single-server-ubuntu.template). Kindly provide some feedback

When I try to create the server from the cloud formation template I get the below error:

![image](https://user-images.githubusercontent.com/38304234/118728400-f2e01700-b7e8-11eb-842a-727b9513a71f.png)

![image](https://user-images.githubusercontent.com/38304234/118728497-20c55b80-b7e9-11eb-91ca-29a2c4ba1c44.png)

**Comment by growak** [comment]
I had the same issue.
There is a problem with easy_install which is not reading the good package index on ubuntu 16.04 LTS.
I tried to use an ami of the 18.04 LTS. The package resolution problem was fixed but the installation script didn't work anyway.
I didn't have time to investigate and setup Tableau manually with my customer.

The install procedure has changed: https://help.tableau.com/current/guides/everybody-install-linux/en-us/everybody_admin_install_linux.htm

**Comment by gm3jjones** [comment]
I am having the same issue. Does any have a fix or work around?

**Comment by charles-sol-analytica** [comment]
duplicates: https://github.com/aws-quickstart/quickstart-tableau-server/issues/90

**Comment by vsnyc** [comment]
This is no longer relevant, the Quick Start has been updated
