### ISSUE TITLE
Tableau Server creation for single node on Ubuntu fails - Failed to receive 1 resource signal(s) within the specified duration

### ISSUE THREAD

**Issue by privobvanner** [aws-quickstart/quickstart-tableau-server#94]
![image](https://user-images.githubusercontent.com/81187064/127519994-fa13c2af-5604-42e7-8b78-c79d8f0065f6.png)

**Comment by fredenow** [comment]
I had the same issue.
There is a problem with easy_install which is not reading the good package index on ubuntu 16.04 LTS.
I tried to use an ami of the 18.04 LTS. The package resolution problem was fixed but the installation script didn't work anyway.
I didn't have time to investigate and setup Tableau manually with my customer.

The install procedure has changed: https://help.tableau.com/current/guides/everybody-install-linux/en-us/everybody_admin_install_linux.htm

**Comment by charles-sol-analytica** [comment]
duplicates: https://github.com/aws-quickstart/quickstart-tableau-server/issues/90
