### ISSUE TITLE
Issue creating workers after changing job flow type

### ISSUE THREAD

**Issue by cameronbarker1** [aws-quickstart/quickstart-tableau-server#95]
Last year I opened an issue with stack creation failing with interactor license types and this was fixed by using --role all-jobs(Line 736-738). Now using all-jobs results in Primary Server Failed to create, changing jobs to no-flow now gets past Primary Server creation, but fails on worker creation. See below screenshot, if anyone is running into similar issues, help would be much appreciated.
![image](https://user-images.githubusercontent.com/66379174/133502388-fa2de299-eef6-4592-995c-aceebfeb3460.png)

**Comment by vsnyc** [comment]
This is no longer relevant, the Quick Start now only supports a single node installation.
