### ISSUE TITLE
Am looking to upgrade the tableau server to 2021 version in AWS cloud using this template

### ISSUE THREAD

**Issue by Priyadarshini1211** [aws-quickstart/quickstart-tableau-server#98]
Am looking to upgrade the tableau server to 2021 version in AWS cloud using this template. This template was used for 2019 and 2020 version which worked just fine. Post log4j issue Wwe are planning to upgrade to 2021 version by testing in dev

        "TableauServerInstaller": "https://s3-us-west-2.amazonaws.com/tableau-quickstart/tableau-server-2020-1-0.x86_64.rpm"

The above link should work for 2021 version. How can I manage that. Please help

**Comment by vsnyc** [comment]
See PR https://github.com/aws-quickstart/quickstart-tableau-server/pull/100 for details. The Quick Start now picks the latest installer.
